// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmouBFWLeKxsL4FslfVu0PlBYUziMn0ts',
    appId: '1:941730506229:web:37589cb95c941193c72cbc',
    messagingSenderId: '941730506229',
    projectId: 'thuma-mina-9d738',
    authDomain: 'thuma-mina-9d738.firebaseapp.com',
    storageBucket: 'thuma-mina-9d738.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDvLoY1FN37hZw4Ww96WXFmXJEyj86sC4',
    appId: '1:941730506229:android:ba10a68e051c1060c72cbc',
    messagingSenderId: '941730506229',
    projectId: 'thuma-mina-9d738',
    storageBucket: 'thuma-mina-9d738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiUzLUV3s8qhV78gV8MjtGESPQ9d74WIQ',
    appId: '1:941730506229:ios:a236579cf479a21bc72cbc',
    messagingSenderId: '941730506229',
    projectId: 'thuma-mina-9d738',
    storageBucket: 'thuma-mina-9d738.appspot.com',
    iosBundleId: 'com.example.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiUzLUV3s8qhV78gV8MjtGESPQ9d74WIQ',
    appId: '1:941730506229:ios:0d53c0af0e45cc3ac72cbc',
    messagingSenderId: '941730506229',
    projectId: 'thuma-mina-9d738',
    storageBucket: 'thuma-mina-9d738.appspot.com',
    iosBundleId: 'com.example.driver.RunnerTests',
  );
}
